In [ ]:
import numpy as np

#1D Array

arr1=np.array([1,2,3,45,True])
# arr1[4]
# 2D Array

arr2=np.array([[1,2,3,45,5],[2,3,3,4,5],[2,3,4,2,1]])
arr2[:,3]
# 3D Array

arr3=np.array([[[1,2,3,45,5],[2,3,3,4,5],[2,3,4,2,1]],[[1,2,3,46,5],[2,3,3,4,5],[2,3,4,2,1]]])
print(arr3[:,:,3])
#To get the dimention of an array
arr2.ndim
# To get the shape of an array
arr3.shape

[[45  4  2]
 [46  4  2]]


(2, 3, 5)

In [ ]:
# 5 rows and 3 columns
# (5,3)
new=np.array([[1,2,3],[12,13,21],[2,12,1],[1,2,3],[3,2,3]])
new

array([[ 1,  2,  3],
       [12, 13, 21],
       [ 2, 12,  1],
       [ 1,  2,  3],
       [ 3,  2,  3]])

In [ ]:
arr1=np.array([1,2,3,46,1])
arr2=np.array([2,2,3,1,2])

In [ ]:
arr2=np.array([[1,2,3,255,5],[2,3,3,4,5],[2,3,4,2,1]])

In [ ]:
# 5row
# 5colu
# 2
# (2,5,5)

In [ ]:
arr2.reshape((1,3,5))

array([[[  1,   2,   3, 255,   5],
        [  2,   3,   3,   4,   5],
        [  2,   3,   4,   2,   1]]])

In [ ]:
# arange
array1=np.arange(50)
# array1.ndim
# Vertical stack
np.vstack([array1,array1,array1])
a=[[1,2,3]]
b=[[3,2,1]]
c=[[1,2,3]]
# np.hstack([array1,array1])

In [ ]:
# All zeros array
np.zeros((5,3))
# All ones array
np.ones((5,10,5))
# Any other number
np.full((5,10),255)
# Full like an another array
np.full_like(arr2,10)
# To create an array of random integer values in an particular range
np.random.randint(1000,size=(10,5))
# To create an array of random decimal values
np.random.rand(2,10,10)
# To create an identity matrix
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
arr2

array([[  1,   2,   3, 255,   5],
       [  2,   3,   3,   4,   5],
       [  2,   3,   4,   2,   1]])

In [ ]:
abc=arr2.copy()
abc[0,3]=255
abc

array([[  1,   2,   3, 255,   5],
       [  2,   3,   3,   4,   5],
       [  2,   3,   4,   2,   1]])

In [ ]:
# 1 1 1 1 1
# 1 0 0 0 1
# 1 0 9 0 1
# 1 0 0 0 1
# 1 1 1 1 1
arr1=np.ones((5,5),dtype='int')
zero=np.zeros((3,3))
zero[1,1]=9
arr1[1:4,1:4]=zero
print(arr1)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
arr1[1:4,1:4]

array([[0, 0, 0],
       [0, 9, 0],
       [0, 0, 0]])

In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
# Add two matrices
print('add',a+b)
# Substract two matrices
print('sub',a-b)
# Multiply two arrays
print('multiplication',a*b)
# To find out the matrix multiplication
print(np.dot(a,b))
# The left side matrix column number should be equal to the row number of second matrix




add [[ 6  8]
 [10 12]]
sub [[-4 -4]
 [-4 -4]]
multiplication [[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [ ]:
2*3
3*2
result=2*2

In [ ]:
# To find out the matrix multiplication
a=np.array([1,2,3])
b=np.array([2,1,2])
print(np.dot(a,b))
np.matmul(a,b)

10


10

In [ ]:
# Create an array of shape (4x4) ranging from 0 to 15. And then convert the array into 2x8 shape.
arr1=np.arange(0,16).reshape((4,4))
arr2=arr1.reshape((2,8))
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
arr1=np.identity(4)
arr2=arr1.reshape((4,2,2))
# To find out the determinant of an matrix
np.linalg.det(arr2)




array([0., 0., 0., 0.])

In [ ]:

# Create an array of shape (4,4) with random integers from 0 and 100. And find out the determinant of that matrix.
arr1=np.random.randint(0,101,size=(4,4))
determinant=np.linalg.det(arr1)
determinant
# Inverse of an matrix.
inverse=np.linalg.inv(arr1)
arr1
# inverse
arr3=np.matmul(arr1,inverse)
arr3

array([[ 1.00000000e+00, -3.19189120e-16, -4.30211422e-16,
         2.60208521e-17],
       [-3.46944695e-17,  1.00000000e+00, -2.08166817e-16,
         1.92554306e-16],
       [ 1.59594560e-16, -1.52655666e-16,  1.00000000e+00,
        -7.80625564e-17],
       [ 2.70616862e-16, -9.71445147e-17, -2.63677968e-16,
         1.00000000e+00]])

In [ ]:
# (x1,y1)
# (x2,y2)
x1=np.array([4,8])
x2=np.array([7,16])
np.linalg.norm(x2-x1)


8.54400374531753

In [ ]:
# Statistical analysis
arr1=np.array([[4,1,2],[7,4,9],[23,12,1]])

print('Minimum value from the entire array',arr1)
# To find out the minimum value from the arr1
print('Minimum value along with rows',np.min(arr1,axis=1))

# To get minimum along with different axis
# axis=0 means columns
# axis=1 means rows
# Maximum value
print('Max value from entire array',np.max(arr1))
print('row-wise max value',np.max(arr1,axis=1))





Minimum value from the entire array [[ 4  1  2]
 [ 7  4  9]
 [23 12  1]]
Minimum value along with rows [1 4 1]
Max value from entire array 23
row-wise max value [ 4  9 23]


In [ ]:
print(arr1)

[[ 4  1  2]
 [ 7  4  9]
 [23 12  1]]


In [ ]:
# argmax and argmin

np.argmax(arr1,axis=1)
np.argmin(arr1,axis=0)
# print(np.where(arr1==23))
# to find sum
np.sum(arr1)
# To find out mean
np.mean(arr1)
# Median
np.median(arr1)
# Standard deviation
np.std(arr1)
# Variance
variance=np.var(arr1)
# square root
np.sqrt(variance)
np.std(arr1)

6.666666666666667

In [ ]:
print(arr1)

[[ 4  1  2]
 [ 7  4  9]
 [23 12  1]]


In [ ]:
# Advanced indexing and Boolean indexing
arr1[(arr1>10)|(arr1<20)]

# Advanced indexing

arr1[:,[2,0]]=1



In [ ]:
arr1

array([[ 1,  1,  1],
       [ 1,  4,  1],
       [ 1, 12,  1]])

In [ ]:
# Create an array of shape (10,6) array with random integers from 1 to 50.
arr1=np.random.randint(1,51,size=(10,6))
arr1

array([[32, 25, 14, 48, 41,  5],
       [43,  5, 49,  5, 24, 29],
       [46,  2, 40, 24, 32, 38],
       [ 6, 30, 16, 30, 12,  7],
       [18, 12, 29,  7, 49, 50],
       [37, 17, 12, 43, 28, 45],
       [15, 22, 46,  6, 28, 26],
       [49, 32, 15, 34, 47, 19],
       [45, 35, 29,  8, 46, 19],
       [28, 41, 50, 47, 34,  3]])

In [ ]:
arr1.size

60

In [ ]:
# Find the column-wise
    # MEAN
    # MEDIAN
    # STD
    # SUM
np.mean(arr1,axis=0)
np.median(arr1,axis=0)
np.std(arr1,axis=0)
np.sum(arr1,axis=0)


array([319, 221, 300, 252, 341, 241])

In [ ]:
np.sum(arr1>25)

35

In [ ]:
arr2=np.array(arr1,dtype='float')
arr2[arr2%7==0]=np.nan
arr2

array([[32., 25., nan, 48., 41.,  5.],
       [43.,  5., nan,  5., 24., 29.],
       [46.,  2., 40., 24., 32., 38.],
       [ 6., 30., 16., 30., 12., nan],
       [18., 12., 29., nan, nan, 50.],
       [37., 17., 12., 43., nan, 45.],
       [15., 22., 46.,  6., nan, 26.],
       [nan, 32., 15., 34., 47., 19.],
       [45., nan, 29.,  8., 46., 19.],
       [nan, 41., 50., 47., 34.,  3.]])

In [ ]:

# Find out the number of element which are greater than 25 and multiple of 7.

# change all numbers which is a multiple of 5 and 7 into np.nan

# Find the determinant of the matrix from the given array with first 6 rows and
# the entire column.
arr2[:7]


# Get the 1st,4th,5th and 7th row of 2,3 columns from the given array.

# Reshape the array into (2,3,10)

# Find out the missing
arr2[:7][np.isnan(arr2[:7])]=0
arr2

array([[32., 25.,  0., 48., 41.,  5.],
       [43.,  5.,  0.,  5., 24., 29.],
       [46.,  2., 40., 24., 32., 38.],
       [ 6., 30., 16., 30., 12.,  0.],
       [18., 12., 29.,  0.,  0., 50.],
       [37., 17., 12., 43.,  0., 45.],
       [15., 22., 46.,  6.,  0., 26.],
       [nan, 32., 15., 34., 47., 19.],
       [45., nan, 29.,  8., 46., 19.],
       [nan, 41., 50., 47., 34.,  3.]])

In [ ]:
# arr2[[1,2,3,4,5,6],[0,1,4,5,2,3]]#43,2,12
arr2[[1,2,3,4,5,6],[0,1,4,5,2,3]]=100


array([[ 32.,  25.,   0.,  48.,  41.,   5.],
       [100.,   5.,   0.,   5.,  24.,  29.],
       [ 46., 100.,  40.,  24.,  32.,  38.],
       [  6.,  30.,  16.,  30., 100.,   0.],
       [ 18.,  12.,  29.,   0.,   0., 100.],
       [ 37.,  17., 100.,  43.,   0.,  45.],
       [ 15.,  22.,  46., 100.,   0.,  26.],
       [ nan,  32.,  15.,  34.,  47.,  19.],
       [ 45.,  nan,  29.,   8.,  46.,  19.],
       [ nan,  41.,  50.,  47.,  34.,   3.]])

In [ ]:
arr3=np.arange(36).reshape((6,6))
arr3[[1,2,4],4:]+=20
arr3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 30, 31],
       [12, 13, 14, 15, 36, 37],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 48, 49],
       [30, 31, 32, 33, 34, 35]])

In [ ]:
arr3[(arr3%7==0)&(arr3%2==0)]


array([ 0, 14])

In [ ]:
arr4=np.genfromtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data',delimiter=',',dtype='str')
arr4

array([['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.0', '1.4', '0.2', 'Iris-setosa'],
       ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
       ['4.6', '3.1', '1.5', '0.2', 'Iris-setosa'],
       ['5.0', '3.6', '1.4', '0.2', 'Iris-setosa'],
       ['5.4', '3.9', '1.7', '0.4', 'Iris-setosa'],
       ['4.6', '3.4', '1.4', '0.3', 'Iris-setosa'],
       ['5.0', '3.4', '1.5', '0.2', 'Iris-setosa'],
       ['4.4', '2.9', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.1', '1.5', '0.1', 'Iris-setosa'],
       ['5.4', '3.7', '1.5', '0.2', 'Iris-setosa'],
       ['4.8', '3.4', '1.6', '0.2', 'Iris-setosa'],
       ['4.8', '3.0', '1.4', '0.1', 'Iris-setosa'],
       ['4.3', '3.0', '1.1', '0.1', 'Iris-setosa'],
       ['5.8', '4.0', '1.2', '0.2', 'Iris-setosa'],
       ['5.7', '4.4', '1.5', '0.4', 'Iris-setosa'],
       ['5.4', '3.9', '1.3', '0.4', 'Iris-setosa'],
       ['5.1', '3.5', '1.4', '0.3', 'Iris-setosa'],
       ['5.7', '3.8', '1.7', '0.3', 'Iris-setosa'],
       ['5.1

In [ ]:
arr4[:,0][arr4[:,-1]=='Iris-versicolor']

array(['7.0', '6.4', '6.9', '5.5', '6.5', '5.7', '6.3', '4.9', '6.6',
       '5.2', '5.0', '5.9', '6.0', '6.1', '5.6', '6.7', '5.6', '5.8',
       '6.2', '5.6', '5.9', '6.1', '6.3', '6.1', '6.4', '6.6', '6.8',
       '6.7', '6.0', '5.7', '5.5', '5.5', '5.8', '6.0', '5.4', '6.0',
       '6.7', '6.3', '5.6', '5.5', '5.5', '6.1', '5.8', '5.0', '5.6',
       '5.7', '5.7', '6.2', '5.1', '5.7'], dtype='<U15')

In [ ]:
# the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
# Less than 3 --> 'small'
# 3-5 --> 'medium'
# '>=5 --> 'large’
new=np.array(arr4[:,2],dtype='float')
new1=arr4[:,2]

new1[new<3]='Small'
new1[(new>=3)&(new<5)]='Medium'


array(['Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Medium', 'Medium', 'Medium', 'Medium', 'Medium',
       'Medium', 'Medium', 'Medium', 'Medium', 'Medium', 'Medium',
       'Medium', 'Medium', 'Medium', 'Medium', 'Medium', 'Medium',
       'Medium', 'Medium', 'Medium', 'Medium', 'Medium', 'Medium',
       'Medium', 'Medium', 'Medium', 'Medium', '5.0', 'Medium', 'Medium',
       'Medium', 'Medium', 'Medium', '5.1', 'Medium', 'Medium', 'Medium',
       'Medium', 'Medium', 'Medium', 'Medium', 'Medium', 'Medium',
       'Medium', 'Medium', '

In [ ]:
new1[new>=5]='large'


In [ ]:
new1

array(['Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Medium', 'Medium', 'Medium', 'Medium', 'Medium',
       'Medium', 'Medium', 'Medium', 'Medium', 'Medium', 'Medium',
       'Medium', 'Medium', 'Medium', 'Medium', 'Medium', 'Medium',
       'Medium', 'Medium', 'Medium', 'Medium', 'Medium', 'Medium',
       'Medium', 'Medium', 'Medium', 'Medium', 'large', 'Medium',
       'Medium', 'Medium', 'Medium', 'Medium', 'large', 'Medium',
       'Medium', 'Medium', 'Medium', 'Medium', 'Medium', 'Medium',
       'Medium', 'Medium', 'Medium', 'Medium